Add policy for private DNS zone groups configuration for Static Web Apps
Azure/Community-Policy pull request #444
Opened 2024-04-28 08:16 UTC by digitmj

2024-05-01 15:08 UTC, Joshua-Donovan requested changes
A couple of small changes are needed before we can approve this pull request, please let me know if you have questions.

2024-05-02 10:56 UTC, digitmj commented on policyDefinitions/App Service/configure-a-private-dns-zone-for-static-webapp/azurepolicy.json
> +        "defaultValue": "/subscriptions/2d028fdd-9fba-467a-8180-722e8ac4d690/resourceGroups/sharedresources/providers/Microsoft.Network/privateDnsZones/privatelink.azurestaticapps.net"
Understandable, I've removed the defaultValue here.

2024-05-02 10:56 UTC, digitmj commented on policyDefinitions/App Service/configure-a-private-dns-zone-for-static-webapp/azurepolicy.parameters.json
> +    "defaultValue": "/subscriptions/2d028fdd-9fba-467a-8180-722e8ac4d690/resourceGroups/sharedresources/providers/Microsoft.Network/privateDnsZones/privatelink.azurestaticapps.net"
Understandable, I've removed the defaultValue here.

2024-05-02 10:57 UTC, digitmj commented on policyDefinitions/App Service/configure-a-private-dns-zone-for-static-webapp/azurepolicy.json
> +            "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7"
In my testing environment it seems to work somehow, but you're right, Reader RBAC role isn't sufficient. Updated the guid to the guid of Network Contributor.

2024-05-02 10:57 UTC, digitmj commented on policyDefinitions/App Service/configure-a-private-dns-zone-for-static-webapp/azurepolicy.rules.json
> +        "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7"
In my testing environment it seems to work somehow, but you're right, Reader RBAC role isn't sufficient. Updated the guid to the guid of Network Contributor.

2024-05-07 16:29 UTC, Joshua-Donovan commented
Thank you @digitmj for updating the policy, the team will review for final pull request approval. Have a great day!

2024-05-14 14:46 UTC, Joshua-Donovan approved these changes

2024-05-15 15:18 UTC, merged